version: 2
jobs:
  build:

    working_directory: ~/jisp

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - run: ./gradlew test

      - store_test_results:
          path: target/surefire-reports

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit